### ISSUE TITLE
Getting ssh: handshake failed: fingerprint mismatch

### ISSUE THREAD

**Issue by ayushmishra2005** [nicklasfrahm/scp-action#2]
I am trying to download remote files from server to local github action using below script:

```
- name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.SSH_HOST }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_fingerprint: ${{ secrets.SSH_PROXY_FINGERPRINT }}
          proxy_username: ${{ secrets.SSH_USER }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: foo/bar.rs
          target: ./foo/bar.rs    
```

I am getting `❌ Failed to connect to target: ssh: handshake failed: fingerprint mismatch`

@nicklasfrahm Please help me to fix this.

**Comment by nicklasfrahm** [comment]
@ayushmishra2005 Are you using a bastion host like I do or do you have a single server?

**Comment by ayushmishra2005** [comment]
@nicklasfrahm I didn’t understand your question. I am able to upload using https://github.com/appleboy/scp-action. I also created an issue there https://github.com/appleboy/scp-action/issues/54

**Comment by nicklasfrahm** [comment]
@ayushmishra2005 My action enforces fingerprint validation for security reasons. That is why the other action works, but mine not.

But let's see how we can get that running for you! Did you have a look at [this section of the README.md](https://github.com/nicklasfrahm/scp-action#using-host-fingerprint-verification)?

If yes and you are still having problems, let me know.

**Comment by ayushmishra2005** [comment]
yes, @nicklasfrahm I followed the same to generate the fingerprint. Please find below the script, which I am using. I removed proxy portion, since I want to download from server to github action.


```
- name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.SSH_HOST }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          port: ${{ secrets.SSH_PORT }}
          source: foo/bar.rs
          target: ./foo/bar.rs    
```
