### ISSUE TITLE
It does not work with act and require fingerprint

### ISSUE THREAD

**Issue by andrius** [nicklasfrahm/scp-action#3]
Hello, I was trying all the options: 20, "20", 20s, "20s" and always receive this error below. I am using act to test workflow

```
[Deployment/Prepare the environment]   🐳  docker run image=ghcr.io/nicklasfrahm/scp-action:main platform= entrypoint=[] cmd=[]
| 2021/06/15 10:22:59 ❌ Failed to parse action timeout: time: invalid duration "${{ inputs.action_timeout }}"
```

If I push the code, then I get another error through GitHub action  log:

```
2021/06/15 10:35:59 ❌ Failed to connect to target: ssh: handshake failed: fingerprint mismatch: server fingerprint: blah
```

```yml
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@v0.3.0
        with:
          direction: download
          timeout: "5s"
          action_timeout: "20s"
```
